name: wheather_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Networking
  http: ^0.13.6

  # Date formatting
  intl: ^0.18.1

  # Weather icons
  weather_icons: ^3.0.0

  # Animations
  flutter_spinkit: ^5.2.0       # Loading spinners
  animated_text_kit: ^4.2.2     # Animated text effects
  lottie: ^2.7.0                # JSON-based animations

  # State management (optional)
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/animations/rain.json
    - assets/animations/cloudy.json
    - assets/animations/snowfall.json
    - assets/animations/sunny.json
